---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine:latest
  environment:
    SSH_PRIVATE_KEY:
      from_secret: SECRET_SSH_PRIVATE_KEY
  commands:
  - 'which ssh-agent || ( apk add --update openssh )'
  - eval "$(ssh-agent -s)"
  - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
  - ssh -o StrictHostKeyChecking=no dronehelper@tiamon.zeue.net -p 58879 'bin/unnamed-domain-update.sh'