---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine:latest
  environment:
    SSH_PRIVATE_KEY:
      from_secret: SECRET_SSH_PRIVATE_KEY
  commands:
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - ssh user1@server1 'df -H'