---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine:latest
  environment:
    SSH_PRIVATE_KEY:
      from_secret: SECRET_SSH_PRIVATE_KEY
  commands:
  - which ssh-agent || ( apk --update add openssh-client ) $ eval $(ssh-agent -s) $ echo "$SSH_PRIVATE_KEY" | ssh-add -
  - ssh zeuedude@tiamon.zeue.net 'df -H'