stages:
  - deploy_to_gitlab_wiki

deploy_to_gitlab_wiki:
  stage: deploy_to_gitlab_wiki
  image: busybox:latest
  script:
    - git clone git@gitlab.zeue.net:unnamed.group/unnamed-domain.git ~/repo-git
    - git clone git@gitlab.zeue.net:unnamed.group/unnamed-domain.wiki.git ~/wiki-git
    - cd ~/wiki-git
    - rm -rf * && cp -r ~/repo-git/wiki/* ./
  only:
    changes: ["wiki/**/*"]
