stages:
  - publish
  - deploy

before_script:
  - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - docker login -u _json_key --password-stdin https://eu.gcr.io < ${HOME}/gcloud-service-key.json

publish:
  stage: publish
  image: google/cloud-sdk:latest
  script:
    - docker build -t $CI_PROJECT_NAME .
    - docker tag $CI_PROJECT_NAME "eu.gcr.io/$GCLOUD_PROJECT_ID/gitlab-ci/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
    - docker push "eu.gcr.io/$GCLOUD_PROJECT_ID/gitlab-ci/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest"
  only:
    - master

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - google-cloud-sdk/bin/gcloud --quiet beta run deploy dnd-unnamed-group --image "eu.gcr.io/$GCLOUD_PROJECT_ID/gitlab-ci/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest" --platform managed --region europe-west1 --project $GCLOUD_PROJECT_ID --allow-unauthenticated
  only:
    - master
