include:
  - "_assets"

defaults:
  - scope:
      path: "" # all
    values:
      layout: "default"
  - scope:
      path: "_assets/images"
    values:
      image: true

permalink: /:title

collections:
  assets:
    output: true
  characters:
    output: true
    sort_by: rating
  rulesets:
    output: true
