defaults:
  - scope:
      path: ""
    values:
      layout: "default"
last-modified-at:
  date-format: "%d-%b-%y"
collections:
  characters:
    output: true
  organizations:
    output: true
  rulesets:
    output: true
  texts:
    output: true
