backend:
  name: github
  repo: zuedev/worlds
media_folder: "assets"
collections:
  - label: "Eldragiir Rulesets"
    name: "eldragiir-rulesets"
    folder: "eldragiir/rulesets"
    create: true
    fields:
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
