backend:
  name: github
  repo: zuedev/worlds
media_folder: "_assets/img"
collections:
  - label: "EldragiirCharacters"
    name: "eldragiircharacters"
    folder: "_eldragiir/characters"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
