backend:
  name: github
  repo: zuedev/worlds
media_folder: "_assets/img"
collections:
  - name: "eldragiir/characters"
    label: "Eldragiir/Characters"
    folder: "_posts/eldragiir/characters"
    fields:
      - { name: Title }
