backend:
  name: github
  repo: zuedev/worlds
media_folder: "assets"
collections:
  - label: "Eldragiir Rulesets"
    name: "eldragiir-rulesets"
    folder: "eldragiir/rulesets"
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
